### ISSUE TITLE
Hard coded `ojkwon` path in plugin?

### ISSUE THREAD

**Issue by elado** [kwonoj/swc-plugin-formatjs#49] opened 2022-10-01 18:06 UTC
Specifically with this code commented I encountered an error that contains `/Users/ojkwon/github/...`

```js
import { transformSync } from "@swc/core";

const src = `
// import { FormattedMessage } from "react-intl";

// export function App() {
//   return (
//     <div>
//       <FormattedMessage defaultMessage="Hello" description="Hello!" />
//     </div>
//   );
// }
console.log(1);
`;

const result = transformSync(src, {
  jsc: {
    parser: {
      syntax: "typescript",
      tsx: true,
    },
    transform: {
      react: {
        runtime: "automatic",
      },
    },
    experimental: {
      plugins: [
        [
          "SWC-plugin-formatjs",
          {
            idInterpolationPattern: "[sha512:contenthash:base64:6]",
            removeDefaultMessage: true,
          },
        ],
      ],
    },
  },
});

console.log(result);
```

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/ojkwon/github/swc-plugin-formatjs/packages/swc-formatjs-visitor/src/lib.rs:859:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'None'

Caused by:
    0: failed to invoke `SWC-plugin-formatjs` as js transform plugin at node_modules/SWC-plugin-formatjs/target/wasm32-wasi/release/swc_plugin_formatjs.wasm
    1: RuntimeError: unreachable
    2: unreachable

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_raise_trap
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: <unknown>
   8: <unknown>', /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/swc-0.230.9/src/plugin.rs:228:14
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
/Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/node_modules/@swc/core/index.js:241
            return bindings.transformSync(isModule ? JSON.stringify(src) : src, isModule, toBuffer(newOptions));
                            ^

Error: failed to handle: failed to invoke plugin: failed to invoke plugin on 'None'

Caused by:
    0: failed to invoke `SWC-plugin-formatjs` as js transform plugin at node_modules/SWC-plugin-formatjs/target/wasm32-wasi/release/swc_plugin_formatjs.wasm
    1: RuntimeError: unreachable
    2: unreachable

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_raise_trap
   2: _napi_register_module_v1
   3: _napi_register_module_v1
   4: _napi_register_module_v1
   5: _napi_register_module_v1
   6: _napi_register_module_v1
   7: <unknown>
   8: <unknown>

Stack backtrace:
   0: _napi_register_module_v1
   1: _wasmer_vm_raise_trap
   2: <unknown>
   3: <unknown>
    at Compiler.transformSync (/Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/node_modules/@swc/core/index.js:241:29)
    at transformSync (/Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/node_modules/@swc/core/index.js:348:21)
    at file:///Users/elad.ossadon/dev/tmp/swc-plugin-formatjs-test/transform.js:18:16
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:61:12) {
  code: 'GenericFailure'
}
```

**Comment by simontaisne** [comment] 2022-10-03 20:26
Same issue here!

**Comment by kwonoj** [comment] 2022-10-03 20:29
This is not a bug, simply due to publish was done on local machine instead of automated one.

I do not have strict plan for automating build pipeline for now, since it is unclear the future of the code location depends on if it goes to upstream (https://github.com/formatjs/formatjs/issues/3589) or stay as independent plugin.

This may or may not be fixed in the future build but I cannot guarantee something for now. Plugin throwing error itself, is a obvious issue in opposite.

**Closed as completed by kwonoj** 2022-10-03 20:29 UTC

**Comment by simontaisne** [comment] 2022-10-03 21:07
Hey @kwonoj! I know that the future of this plugin is still uncertain, but in its current version, as I understand it, it's simply not usable.

With the latest Next.js version, configuring the plugin (even without any option)...

```
  experimental: {
    swcPlugins: [['SWC-plugin-formatjs', {}]],
  },
```

...results in error 🤔

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /Users/ojkwon/github/swc-plugin-formatjs/packages/swc-formatjs-visitor/src/lib.rs:859:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

By the way, I really appreciate you taking the time to start the port to swc, and looking at this [thread](https://github.com/vercel/next.js/discussions/30174#discussioncomment-1539820), I'm sure I'm not the only one.

**Comment by kwonoj** [comment] 2022-10-03 21:08
@simontaisne You're referring incorrect issue, this issue is not for the error itself but for the build path. https://github.com/kwonoj/swc-plugin-formatjs/issues/48
